### ISSUE TITLE
Sequence Diagram Update

### ISSUE THREAD

**Issue by corupta** [bounswe/bounswe2019group9#44] opened 2019-03-22 17:45 UTC
Since, the time is running short and there are lots of things to change/make, reviewers are merged with the creators as well as aditional members to make the next version. All of the assignees are expected to help finish sequence diagrams as soon as possible.

**Comment by uskudarli** [comment] 2019-03-24 20:21
Needs some description, right?

Who is responsible for updating which diagram? It would be easier to track by designating the task and assigning to a specific person. That way it is clear who has what responsibility.

Once done, it can be assigned to someone else to review.

**Closed** 2019-03-25 04:46 UTC
Labels: type : enhancement, urgency : emergent
